# -*- coding: utf-8 -*-
import os

PROJECT_ROOT = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))

REDIS_LUA_SEARCH_ITEM = 0
REDIS_LUA_CALCULATE_AVERAGE_ORDER = 0
REDIS_LUA_UPDATE_CONNECTED_ITEM = 0
REDIS_LUA_GET_ITEMS_FROM_ID_LIST = 0

ALLOWED_ATTRIBUTES = set(["title","color", "image", "parent"])

BASE_STRUCTURE_MUSIC_CATEGORY = ""
BASE_STRUCTURE_MOVIE_CATEGORY = ""
BASE_STRUCTURE_FOUND_BUGS_CATEGORY = ""
